import fs from 'node:fs';
import path from 'node:path';
import Link from 'next/link';
import type { MetaJson, VariableDef } from '@/lib/strata-types';

// Server-side build-time read. The about page is static, so this runs
// once at build and the result is inlined into the HTML for /about. No
// client-side fetch needed — keeps the page snappy and avoids a loading
// spinner on what is fundamentally a documentation page.
function loadMetaAtBuild(): MetaJson {
  const file = path.join(process.cwd(), 'public', 'data', 'meta.json');
  return JSON.parse(fs.readFileSync(file, 'utf-8')) as MetaJson;
}

interface DomainBreakdown {
  domain: string;
  total: number;
  inCleaned: number;
  exploded: number;
  externalText: number;
  needsExpansion: number;
  missing: number;
}

function breakdownByDomain(variables: VariableDef[]): DomainBreakdown[] {
  const map = new Map<string, DomainBreakdown>();
  for (const v of variables) {
    let row = map.get(v.domain);
    if (!row) {
      row = {
        domain: v.domain,
        total: 0,
        inCleaned: 0,
        exploded: 0,
        externalText: 0,
        needsExpansion: 0,
        missing: 0,
      };
      map.set(v.domain, row);
    }
    row.total++;
    switch (v.data_availability) {
      case 'in_cleaned_csv':
        row.inCleaned++;
        break;
      case 'in_cleaned_csv_exploded':
        row.exploded++;
        break;
      case 'external_text_files':
        row.externalText++;
        break;
      case 'needs_runtime_expansion':
        row.needsExpansion++;
        break;
      case 'missing':
        row.missing++;
        break;
    }
  }
  return Array.from(map.values()).sort((a, b) => b.total - a.total);
}

export default function AboutPage() {
  const meta = loadMetaAtBuild();
  const totalVars = meta.variables.length;
  const analyzable = meta.variables.filter(
    (v) =>
      v.data_availability === 'in_cleaned_csv' ||
      v.data_availability === 'in_cleaned_csv_exploded',
  ).length;
  const byDomain = breakdownByDomain(meta.variables);
  const generatedAt = new Date(meta.generated_at).toLocaleString('en-US', {
    dateStyle: 'long',
    timeStyle: 'short',
  });

  return (
    <article className="mx-auto max-w-3xl px-6 py-12 space-y-12">
      <header className="space-y-3">
        <p
          className="text-xs text-slate uppercase tracking-wide"
          style={{ fontFamily: 'var(--font-mono)' }}
        >
          About
        </p>
        <h1
          className="text-4xl text-plum"
          style={{ fontFamily: 'var(--font-serif)' }}
        >
          Methodology &amp; attribution
        </h1>
        <p className="text-lg text-ink/80 leading-relaxed">
          Strata is a static explorer for the precomputed outputs of the
          UAS social-media panel survey (UAS514–UAS519). Every chart you
          see is a slice of a JSON file generated by a documented R
          pipeline. Nothing is computed on the fly.
        </p>
      </header>

      <section className="space-y-3">
        <h2 className="text-2xl text-plum" style={{ fontFamily: 'var(--font-serif)' }}>
          Survey waves
        </h2>
        <p className="text-ink/85 leading-relaxed">
          Six waves of the Understanding America Study were collected
          between 2023 and 2025. Each row below shows the field dates and
          the unweighted sample size in the cleaned panel that Strata
          serves.
        </p>
        <div className="overflow-x-auto">
          <table
            className="w-full text-sm border-collapse"
            style={{ fontFamily: 'var(--font-mono)' }}
          >
            <thead>
              <tr className="border-b border-mist text-slate">
                <th className="text-left py-2 pr-4">Wave</th>
                <th className="text-left py-2 pr-4">UAS #</th>
                <th className="text-left py-2 pr-4">Field dates</th>
                <th className="text-right py-2 pr-4">Targeted n</th>
                <th className="text-right py-2 pr-4">Completed n</th>
                <th className="text-right py-2">n in cleaned</th>
              </tr>
            </thead>
            <tbody>
              {meta.waves.map((w) => (
                <tr key={w.wave} className="border-b border-mist/60">
                  <td className="py-2 pr-4">Wave {w.wave}</td>
                  <td className="py-2 pr-4">UAS{w.uas_num}</td>
                  <td className="py-2 pr-4 text-ink">{w.dates}</td>
                  <td className="py-2 pr-4 text-right">
                    {w.targeted_n.toLocaleString()}
                  </td>
                  <td className="py-2 pr-4 text-right">
                    {w.completed_n.toLocaleString()}
                  </td>
                  <td className="py-2 text-right">
                    {w.n_in_cleaned.toLocaleString()}
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </section>

      <section className="space-y-3">
        <h2 className="text-2xl text-plum" style={{ fontFamily: 'var(--font-serif)' }}>
          Variable coverage
        </h2>
        <p className="text-ink/85 leading-relaxed">
          The Phase 0 data dictionary catalogs <strong>{totalVars}</strong>{' '}
          variables across {byDomain.length} survey domains.{' '}
          <strong>{analyzable}</strong> of those have analyzable rows in
          the precomputed JSONs — the remainder are reserved for free-
          response text (which lives outside the public repo) or items
          that require additional runtime expansion not implemented for
          v0.1.0.
        </p>
        <div className="overflow-x-auto">
          <table
            className="w-full text-sm border-collapse"
            style={{ fontFamily: 'var(--font-mono)' }}
          >
            <thead>
              <tr className="border-b border-mist text-slate">
                <th className="text-left py-2 pr-4">Domain</th>
                <th className="text-right py-2 pr-4">Vars</th>
                <th className="text-right py-2 pr-4">Analyzable</th>
                <th className="text-right py-2 pr-4">Text-only</th>
                <th className="text-right py-2">Other</th>
              </tr>
            </thead>
            <tbody>
              {byDomain.map((d) => {
                const analyzableCount = d.inCleaned + d.exploded;
                const other = d.needsExpansion + d.missing;
                return (
                  <tr key={d.domain} className="border-b border-mist/60">
                    <td className="py-2 pr-4 text-ink">{d.domain}</td>
                    <td className="py-2 pr-4 text-right">{d.total}</td>
                    <td className="py-2 pr-4 text-right">{analyzableCount}</td>
                    <td className="py-2 pr-4 text-right">
                      {d.externalText || ''}
                    </td>
                    <td className="py-2 text-right">{other || ''}</td>
                  </tr>
                );
              })}
              <tr className="font-medium text-ink">
                <td className="py-2 pr-4">Total</td>
                <td className="py-2 pr-4 text-right">{totalVars}</td>
                <td className="py-2 pr-4 text-right">{analyzable}</td>
                <td className="py-2 pr-4 text-right">
                  {byDomain.reduce((s, d) => s + d.externalText, 0)}
                </td>
                <td className="py-2 text-right">
                  {byDomain.reduce(
                    (s, d) => s + d.needsExpansion + d.missing,
                    0,
                  )}
                </td>
              </tr>
            </tbody>
          </table>
        </div>
      </section>

      <section className="space-y-3">
        <h2 className="text-2xl text-plum" style={{ fontFamily: 'var(--font-serif)' }}>
          Suppression
        </h2>
        <p className="text-ink/85 leading-relaxed">
          Cells with fewer than{' '}
          <strong>{meta._meta.cell_floor} respondents</strong> are
          suppressed by design. The underlying JSON rows are emitted with
          all statistic fields set to <code className="text-sm">null</code>{' '}
          and a <code className="text-sm">suppressed: true</code> flag,
          rather than being omitted. Strata renders an &ldquo;insufficient
          n&rdquo; placeholder when it encounters one. The exact policy
          documented in <code className="text-sm">meta.json</code>:
        </p>
        <blockquote className="border-l-2 border-mulberry pl-4 text-ink/85 italic">
          {meta._meta.suppression_policy}
        </blockquote>
      </section>

      <section className="space-y-3">
        <h2 className="text-2xl text-plum" style={{ fontFamily: 'var(--font-serif)' }}>
          Weighting
        </h2>
        <p className="text-ink/85 leading-relaxed">
          Every precomputed row carries both <em>unweighted</em> and{' '}
          <em>weighted</em> estimates (<code className="text-sm">value</code>{' '}
          and <code className="text-sm">weighted_value</code>, with
          matching standard errors, confidence intervals, and effective
          sample sizes). UAS provides probability weights to adjust for
          panel design and non-response; weighted estimates are
          generalizable to U.S. adults at the time of each wave, while
          unweighted estimates describe the panel itself. Strata defaults
          to <strong>weighted</strong> and offers an explicit toggle.
        </p>
      </section>

      <section className="space-y-3">
        <h2 className="text-2xl text-plum" style={{ fontFamily: 'var(--font-serif)' }}>
          Correlations
        </h2>
        <p className="text-ink/85 leading-relaxed">
          All pairwise correlations in Strata are <strong>Spearman&rsquo;s
          ρ</strong>, computed per wave. Spearman handles ordinal Likert
          and skewed count variables better than Pearson and does not
          assume a linear relationship. Where the underlying scale is
          reverse-coded, the flip is applied at the cleaning stage; the
          UI does not need to re-flip. Correlation is not causation, and
          small samples or small <em>ρ</em> values should be interpreted
          with caution.
        </p>
      </section>

      <section className="space-y-3">
        <h2 className="text-2xl text-plum" style={{ fontFamily: 'var(--font-serif)' }}>
          Cite this tool
        </h2>
        <p className="text-ink/85 leading-relaxed">
          For aggregate citation:
        </p>
        <pre
          className="bg-mist/50 border border-mist rounded-md p-4 text-sm overflow-x-auto"
          style={{ fontFamily: 'var(--font-mono)' }}
        >
{`Motyl, M. (2026). Ground Truth Strata (v0.1.0)
  [Data explorer for the UAS social-media panel survey].
  https://strata.mattmotyl.com`}
        </pre>
        <p className="text-ink/85 leading-relaxed">
          Individual findings have a per-chart citation block that records
          variable, wave, weighting status, and the precomputed-JSON
          generated timestamp.
        </p>
      </section>

      <section className="space-y-3">
        <h2 className="text-2xl text-plum" style={{ fontFamily: 'var(--font-serif)' }}>
          Required UAS attribution
        </h2>
        <p className="text-ink/85 leading-relaxed">
          These data are from survey(s) administered by the Understanding
          America Study, which is maintained by the Center for Economic
          and Social Research (CESR) at the University of Southern
          California. The outputs of Strata are the responsibility of its
          users and do not necessarily represent the official views of
          USC or UAS. The tool should be considered an early beta-level
          app and results should be confirmed with the raw data.
          Consistent with open science practices, any individual is able
          to access these data for purpose of replication or research
          after free registration with the Understanding America Study (
          <a
            href="https://uasdata.usc.edu/page/Registration+Form"
            className="text-mulberry hover:text-plum underline"
          >
            uasdata.usc.edu/page/Registration+Form
          </a>
          ), and provision of a signed data use agreement. You may also
          communicate with this tool&rsquo;s creator via email or GitHub
          requests (
          <a
            href="https://github.com/mattmotyl/ground-truth-strata"
            className="text-mulberry hover:text-plum underline"
          >
            github.com/mattmotyl/ground-truth-strata
          </a>
          ).
        </p>
      </section>

      <footer className="pt-8 border-t border-mist text-xs text-slate space-y-1" style={{ fontFamily: 'var(--font-mono)' }}>
        <p>Precomputed JSON generated: {generatedAt}</p>
        <p>Pipeline: {meta._meta.generated_by}</p>
        <p>Source data: {meta._meta.source_data}</p>
        <p>Source dictionary: {meta._meta.source_dictionary}</p>
        <p className="pt-2">
          <Link href="/" className="text-mulberry hover:text-plum">
            ← Back to Strata
          </Link>
        </p>
      </footer>
    </article>
  );
}
